# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nodeapi/nodeapi.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nodeapi/nodeapi.proto',
  package='nodeapi',
  syntax='proto3',
  serialized_options=b'Z\"github.com/synerex/synerex_nodeapi',
  serialized_pb=b'\n\x15nodeapi/nodeapi.proto\x12\x07nodeapi\"\xd6\x01\n\x08NodeInfo\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12$\n\tnode_type\x18\x02 \x01(\x0e\x32\x11.nodeapi.NodeType\x12\x13\n\x0bserver_info\x18\x03 \x01(\t\x12\x1a\n\x12node_pbase_version\x18\x04 \x01(\t\x12\x14\n\x0cwith_node_id\x18\x05 \x01(\x05\x12\x12\n\ncluster_id\x18\x06 \x01(\x05\x12\x0f\n\x07\x61rea_id\x18\x07 \x01(\t\x12\x14\n\x0c\x63hannelTypes\x18\x08 \x03(\r\x12\x0f\n\x07gw_info\x18\t \x01(\t\"Z\n\x06NodeID\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0e\n\x06secret\x18\x02 \x01(\x06\x12\x13\n\x0bserver_info\x18\x03 \x01(\t\x12\x1a\n\x12keepalive_duration\x18\x04 \x01(\x05\">\n\x0cServerStatus\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x01\x12\x0e\n\x06memory\x18\x02 \x01(\x01\x12\x11\n\tmsg_count\x18\x03 \x01(\x04\"\x91\x01\n\nNodeUpdate\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0e\n\x06secret\x18\x02 \x01(\x06\x12\x14\n\x0cupdate_count\x18\x03 \x01(\x05\x12\x13\n\x0bnode_status\x18\x04 \x01(\x05\x12\x10\n\x08node_arg\x18\x05 \x01(\t\x12%\n\x06status\x18\x06 \x01(\x0b\x32\x15.nodeapi.ServerStatus\"O\n\x08Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12*\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x19.nodeapi.KeepAliveCommand\x12\x0b\n\x03\x65rr\x18\x03 \x01(\t*1\n\x08NodeType\x12\x0c\n\x08PROVIDER\x10\x00\x12\n\n\x06SERVER\x10\x01\x12\x0b\n\x07GATEWAY\x10\x02*W\n\x10KeepAliveCommand\x12\x08\n\x04NONE\x10\x00\x12\r\n\tRECONNECT\x10\x01\x12\x11\n\rSERVER_CHANGE\x10\x02\x12\x17\n\x13PROVIDER_DISCONNECT\x10\x03\x32\xde\x01\n\x04Node\x12\x34\n\x0cRegisterNode\x12\x11.nodeapi.NodeInfo\x1a\x0f.nodeapi.NodeID\"\x00\x12\x31\n\tQueryNode\x12\x0f.nodeapi.NodeID\x1a\x11.nodeapi.NodeInfo\"\x00\x12\x35\n\tKeepAlive\x12\x13.nodeapi.NodeUpdate\x1a\x11.nodeapi.Response\"\x00\x12\x36\n\x0eUnRegisterNode\x12\x0f.nodeapi.NodeID\x1a\x11.nodeapi.Response\"\x00\x42$Z\"github.com/synerex/synerex_nodeapib\x06proto3'
)

_NODETYPE = _descriptor.EnumDescriptor(
  name='NodeType',
  full_name='nodeapi.NodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROVIDER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GATEWAY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=636,
  serialized_end=685,
)
_sym_db.RegisterEnumDescriptor(_NODETYPE)

NodeType = enum_type_wrapper.EnumTypeWrapper(_NODETYPE)
_KEEPALIVECOMMAND = _descriptor.EnumDescriptor(
  name='KeepAliveCommand',
  full_name='nodeapi.KeepAliveCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECONNECT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_CHANGE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROVIDER_DISCONNECT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=687,
  serialized_end=774,
)
_sym_db.RegisterEnumDescriptor(_KEEPALIVECOMMAND)

KeepAliveCommand = enum_type_wrapper.EnumTypeWrapper(_KEEPALIVECOMMAND)
PROVIDER = 0
SERVER = 1
GATEWAY = 2
NONE = 0
RECONNECT = 1
SERVER_CHANGE = 2
PROVIDER_DISCONNECT = 3



_NODEINFO = _descriptor.Descriptor(
  name='NodeInfo',
  full_name='nodeapi.NodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_name', full_name='nodeapi.NodeInfo.node_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_type', full_name='nodeapi.NodeInfo.node_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_info', full_name='nodeapi.NodeInfo.server_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_pbase_version', full_name='nodeapi.NodeInfo.node_pbase_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='with_node_id', full_name='nodeapi.NodeInfo.with_node_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='nodeapi.NodeInfo.cluster_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area_id', full_name='nodeapi.NodeInfo.area_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channelTypes', full_name='nodeapi.NodeInfo.channelTypes', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gw_info', full_name='nodeapi.NodeInfo.gw_info', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=249,
)


_NODEID = _descriptor.Descriptor(
  name='NodeID',
  full_name='nodeapi.NodeID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='nodeapi.NodeID.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret', full_name='nodeapi.NodeID.secret', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_info', full_name='nodeapi.NodeID.server_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keepalive_duration', full_name='nodeapi.NodeID.keepalive_duration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=341,
)


_SERVERSTATUS = _descriptor.Descriptor(
  name='ServerStatus',
  full_name='nodeapi.ServerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='nodeapi.ServerStatus.cpu', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory', full_name='nodeapi.ServerStatus.memory', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_count', full_name='nodeapi.ServerStatus.msg_count', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=405,
)


_NODEUPDATE = _descriptor.Descriptor(
  name='NodeUpdate',
  full_name='nodeapi.NodeUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='nodeapi.NodeUpdate.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret', full_name='nodeapi.NodeUpdate.secret', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_count', full_name='nodeapi.NodeUpdate.update_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_status', full_name='nodeapi.NodeUpdate.node_status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_arg', full_name='nodeapi.NodeUpdate.node_arg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='nodeapi.NodeUpdate.status', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=553,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='nodeapi.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='nodeapi.Response.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='nodeapi.Response.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='nodeapi.Response.err', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=634,
)

_NODEINFO.fields_by_name['node_type'].enum_type = _NODETYPE
_NODEUPDATE.fields_by_name['status'].message_type = _SERVERSTATUS
_RESPONSE.fields_by_name['command'].enum_type = _KEEPALIVECOMMAND
DESCRIPTOR.message_types_by_name['NodeInfo'] = _NODEINFO
DESCRIPTOR.message_types_by_name['NodeID'] = _NODEID
DESCRIPTOR.message_types_by_name['ServerStatus'] = _SERVERSTATUS
DESCRIPTOR.message_types_by_name['NodeUpdate'] = _NODEUPDATE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['NodeType'] = _NODETYPE
DESCRIPTOR.enum_types_by_name['KeepAliveCommand'] = _KEEPALIVECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeInfo = _reflection.GeneratedProtocolMessageType('NodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _NODEINFO,
  '__module__' : 'nodeapi.nodeapi_pb2'
  # @@protoc_insertion_point(class_scope:nodeapi.NodeInfo)
  })
_sym_db.RegisterMessage(NodeInfo)

NodeID = _reflection.GeneratedProtocolMessageType('NodeID', (_message.Message,), {
  'DESCRIPTOR' : _NODEID,
  '__module__' : 'nodeapi.nodeapi_pb2'
  # @@protoc_insertion_point(class_scope:nodeapi.NodeID)
  })
_sym_db.RegisterMessage(NodeID)

ServerStatus = _reflection.GeneratedProtocolMessageType('ServerStatus', (_message.Message,), {
  'DESCRIPTOR' : _SERVERSTATUS,
  '__module__' : 'nodeapi.nodeapi_pb2'
  # @@protoc_insertion_point(class_scope:nodeapi.ServerStatus)
  })
_sym_db.RegisterMessage(ServerStatus)

NodeUpdate = _reflection.GeneratedProtocolMessageType('NodeUpdate', (_message.Message,), {
  'DESCRIPTOR' : _NODEUPDATE,
  '__module__' : 'nodeapi.nodeapi_pb2'
  # @@protoc_insertion_point(class_scope:nodeapi.NodeUpdate)
  })
_sym_db.RegisterMessage(NodeUpdate)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'nodeapi.nodeapi_pb2'
  # @@protoc_insertion_point(class_scope:nodeapi.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_NODE = _descriptor.ServiceDescriptor(
  name='Node',
  full_name='nodeapi.Node',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=777,
  serialized_end=999,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNode',
    full_name='nodeapi.Node.RegisterNode',
    index=0,
    containing_service=None,
    input_type=_NODEINFO,
    output_type=_NODEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryNode',
    full_name='nodeapi.Node.QueryNode',
    index=1,
    containing_service=None,
    input_type=_NODEID,
    output_type=_NODEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='KeepAlive',
    full_name='nodeapi.Node.KeepAlive',
    index=2,
    containing_service=None,
    input_type=_NODEUPDATE,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UnRegisterNode',
    full_name='nodeapi.Node.UnRegisterNode',
    index=3,
    containing_service=None,
    input_type=_NODEID,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODE)

DESCRIPTOR.services_by_name['Node'] = _NODE

# @@protoc_insertion_point(module_scope)
